"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { RefreshCw, Share2, ExternalLink, Users, Headphones, TrendingUp, Calendar, MapPin, Play, Eye, ArrowUp, ArrowDown, Minus, Check } from "lucide-react"

// Format date without timezone issues
function formatDate(dateStr: string) {
  const [year, month, day] = dateStr.split("-").map(Number)
  const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
  return `${months[month - 1]} ${day}`
}

interface EmergingArtist {
  id: string
  name: string
  genre: string
  origin: string
  monthlyListeners: string
  recentRelease: string
  bio: string
  socialFollowers: string
  bandcampUrl: string
  growth: string
}

interface EmergingShow {
  id: string
  artist: string
  venue: string
  date: string
  time: string
  venueLocation: string
  artistOrigin: string
  ticketLink: string
}

interface EmergingTrending {
  id: string
  rank: number
  title: string
  artist: string
  artistOrigin: string
  plays: string
  movement: "up" | "down" | "stable"
  change: number
}

interface EmergingVideo {
  id: string
  title: string
  artist: string
  artistOrigin: string
  views: string
  publishedAt: string
  thumbnail: string
  link: string
}

// Empty array - real artist data would be fetched from an API
const mockArtists: EmergingArtist[] = []

// Empty array - real show data would be fetched from an API
const mockEmergingShows: EmergingShow[] = []

// Empty array - real trending data would be fetched from an API
const mockEmergingTrending: EmergingTrending[] = []

// Empty array - real video data would be fetched from YouTube API
const mockEmergingVideos: EmergingVideo[] = []

export function EmergingArtists() {
  const [isRefreshing, setIsRefreshing] = useState(false)
  const [copiedId, setCopiedId] = useState<string | null>(null)
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
  }, [])

  const handleRefresh = () => {
    setIsRefreshing(true)
    setTimeout(() => setIsRefreshing(false), 1000)
  }

  const copyToClipboard = (artist: EmergingArtist) => {
    const outline = `# Feature: ${artist.name}

## Artist Profile
- Name: ${artist.name}
- From: ${artist.origin}, NJ
- Genre: ${artist.genre}
- Monthly Listeners: ${artist.monthlyListeners}
- Recent Release: ${artist.recentRelease}
- Growth: ${artist.growth} this month

## Bio
${artist.bio}

## Article Outline
1. Introduction - Who is ${artist.name}?
2. ${artist.origin} roots and local scene influence
3. Sound and style breakdown
4. Recent release: "${artist.recentRelease}" review
5. Where to catch them live
6. What's next for ${artist.name}

## Social Presence
- Followers: ${artist.socialFollowers}
- Bandcamp: ${artist.bandcampUrl}

---
Generated by The Gardener Dashboard`
    
    navigator.clipboard.writeText(outline)
    setCopiedId(artist.id)
    setTimeout(() => setCopiedId(null), 2000)
  }

  const getTimeAgo = (date: string) => {
    if (!mounted) return ""
    const [year, month, day] = date.split("-").map(Number)
    const published = new Date(year, month - 1, day)
    const now = new Date()
    now.setHours(0, 0, 0, 0)
    const diffDays = Math.floor((now.getTime() - published.getTime()) / (1000 * 60 * 60 * 24))
    
    if (diffDays === 0) return "Today"
    if (diffDays === 1) return "Yesterday"
    if (diffDays < 7) return `${diffDays} days ago`
    return `${Math.floor(diffDays / 7)} weeks ago`
  }

  const MovementIcon = ({ movement, change }: { movement: string; change: number }) => {
    if (movement === "up") {
      return (
        <span className="flex items-center gap-0.5 text-xs text-primary font-medium">
          <ArrowUp className="h-3 w-3" />
          {change}
        </span>
      )
    }
    if (movement === "down") {
      return (
        <span className="flex items-center gap-0.5 text-xs text-destructive">
          <ArrowDown className="h-3 w-3" />
          {change}
        </span>
      )
    }
    return <Minus className="h-3 w-3 text-muted-foreground" />
  }

  return (
    <div className="grid gap-8 lg:grid-cols-12">
      {/* Left Column - Artist Profiles */}
      <div className="lg:col-span-5">
        <section className="border-t-2 border-foreground pt-4">
          <div className="flex items-center justify-between mb-4 pb-2 border-b border-border">
            <h3 
              className="font-display text-xl md:text-2xl font-bold tracking-tight"
              style={{ fontFamily: 'var(--font-display)' }}
            >
              Rising Artists
            </h3>
            <Button
              variant="ghost"
              size="sm"
              onClick={handleRefresh}
              disabled={isRefreshing}
              className="h-7 w-7 p-0"
            >
              <RefreshCw className={`h-3.5 w-3.5 ${isRefreshing ? "animate-spin" : ""}`} />
            </Button>
          </div>
          
          <div className="space-y-4">
            {mockArtists.length === 0 && (
              <div className="py-8 text-center">
                <Users className="h-8 w-8 mx-auto text-muted-foreground/50 mb-3" />
                <p className="text-sm text-muted-foreground">
                  No emerging artists to display
                </p>
                <p className="text-xs text-muted-foreground/70 mt-1">
                  Connect to a data source for artist profiles
                </p>
              </div>
            )}
            {mockArtists.map((artist) => (
              <article 
                key={artist.id} 
                className="group border-b border-border pb-4 last:border-0"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2 flex-wrap">
                      <h4 className="font-semibold text-foreground leading-tight">
                        {artist.name}
                      </h4>
                      <Badge variant="secondary" className="text-[9px] font-normal px-1.5 py-0">
                        {artist.origin}
                      </Badge>
                    </div>
                    <p className="mt-0.5 text-xs text-muted-foreground italic">
                      {artist.genre}
                    </p>
                    <p className="mt-1 text-sm text-muted-foreground leading-snug">
                      {artist.bio}
                    </p>
                    <div className="mt-2 flex flex-wrap items-center gap-3 text-xs text-muted-foreground">
                      <span className="flex items-center gap-1">
                        <Headphones className="h-3 w-3" />
                        {artist.monthlyListeners}
                      </span>
                      <span className="flex items-center gap-1">
                        <Users className="h-3 w-3" />
                        {artist.socialFollowers}
                      </span>
                      <span className="flex items-center gap-1 text-primary font-medium">
                        <TrendingUp className="h-3 w-3" />
                        {artist.growth}
                      </span>
                    </div>
                  </div>
                  <div className="flex flex-col gap-1">
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => copyToClipboard(artist)}
                      className="h-6 w-6 p-0 opacity-0 group-hover:opacity-100 transition-opacity"
                      title="Share artist"
                    >
                      {copiedId === artist.id ? (
                        <Check className="h-3 w-3 text-primary" />
                      ) : (
                        <Share2 className="h-3 w-3" />
                      )}
                    </Button>
                    <Button
                      variant="ghost"
                      size="sm"
                      asChild
                      className="h-6 w-6 p-0 opacity-0 group-hover:opacity-100 transition-opacity"
                    >
                      <a href={artist.bandcampUrl} target="_blank" rel="noopener noreferrer" title="View on Bandcamp">
                        <ExternalLink className="h-3 w-3" />
                      </a>
                    </Button>
                  </div>
                </div>
              </article>
            ))}
          </div>
        </section>
      </div>

      {/* Center Column - Shows & Trending */}
      <div className="lg:col-span-4 space-y-8">
        {/* Upcoming Shows */}
        <section className="border-t-2 border-foreground pt-4">
          <h3 
            className="font-display text-xl md:text-2xl font-bold tracking-tight mb-4 pb-2 border-b border-border"
            style={{ fontFamily: 'var(--font-display)' }}
          >
            Upcoming Shows
          </h3>
          <div className="space-y-3">
            {mockEmergingShows.length === 0 && (
              <div className="py-6 text-center">
                <Calendar className="h-6 w-6 mx-auto text-muted-foreground/50 mb-2" />
                <p className="text-sm text-muted-foreground">No shows to display</p>
              </div>
            )}
            {mockEmergingShows.map((show) => (
              <article
                key={show.id}
                className="group border-b border-border pb-3 last:border-0 last:pb-0"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-2 flex-wrap">
                      <h4 className="font-semibold text-foreground">{show.artist}</h4>
                      <Badge variant="secondary" className="text-[9px] font-normal px-1.5 py-0">
                        {show.artistOrigin}
                      </Badge>
                    </div>
                    <div className="mt-1 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-muted-foreground">
                      <span className="flex items-center gap-1">
                        <MapPin className="h-3 w-3" />
                        {show.venue} ({show.venueLocation})
                      </span>
                      <span className="flex items-center gap-1">
                        <Calendar className="h-3 w-3" />
                        {formatDate(show.date)} at {show.time}
                      </span>
                    </div>
                  </div>
                </div>
              </article>
            ))}
          </div>
        </section>

        {/* Trending This Week */}
        <section className="border-t border-border pt-4">
          <h3 
            className="font-display text-xl md:text-2xl font-bold tracking-tight mb-4 pb-2 border-b border-border"
            style={{ fontFamily: 'var(--font-display)' }}
          >
            Trending This Week
          </h3>
          <div className="space-y-1">
            {mockEmergingTrending.length === 0 && (
              <div className="py-6 text-center">
                <TrendingUp className="h-6 w-6 mx-auto text-muted-foreground/50 mb-2" />
                <p className="text-sm text-muted-foreground">No trending songs to display</p>
              </div>
            )}
            {mockEmergingTrending.map((song) => (
              <article
                key={song.id}
                className="flex items-center gap-3 py-2 border-b border-border/50 last:border-0"
              >
                <div className="flex h-6 w-6 shrink-0 items-center justify-center text-sm font-bold text-muted-foreground">
                  {song.rank}.
                </div>
                <div className="min-w-0 flex-1">
                  <h4 className="truncate text-sm font-medium text-foreground">{song.title}</h4>
                  <div className="flex items-center gap-2">
                    <p className="truncate text-xs text-muted-foreground">{song.artist}</p>
                    <Badge variant="secondary" className="text-[8px] font-normal px-1 py-0">
                      {song.artistOrigin}
                    </Badge>
                  </div>
                </div>
                <div className="flex shrink-0 items-center gap-2">
                  <span className="text-xs text-muted-foreground">{song.plays}</span>
                  <MovementIcon movement={song.movement} change={song.change} />
                </div>
              </article>
            ))}
          </div>
        </section>
      </div>

      {/* Right Column - Videos */}
      <div className="lg:col-span-3">
        <section className="border-t-2 border-foreground pt-4">
          <h3 
            className="font-display text-xl md:text-2xl font-bold tracking-tight mb-4 pb-2 border-b border-border"
            style={{ fontFamily: 'var(--font-display)' }}
          >
            New Music Videos
          </h3>
          <div className="space-y-4">
            {mockEmergingVideos.length === 0 && (
              <div className="py-6 text-center">
                <Play className="h-6 w-6 mx-auto text-muted-foreground/50 mb-2" />
                <p className="text-sm text-muted-foreground">No videos to display</p>
              </div>
            )}
            {mockEmergingVideos.map((video) => (
              <article key={video.id} className="group">
                <a 
                  href={video.link} 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="block"
                >
                  <div className="relative aspect-video bg-muted rounded overflow-hidden mb-2">
                    <div className="absolute inset-0 flex items-center justify-center">
                      <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/90 transition-transform group-hover:scale-110">
                        <Play className="h-4 w-4 text-primary-foreground ml-0.5" />
                      </div>
                    </div>
                  </div>
                  <h4 className="font-medium text-sm text-foreground leading-tight group-hover:text-primary transition-colors">
                    {video.title}
                  </h4>
                  <div className="flex items-center gap-2 mt-1">
                    <p className="text-xs text-muted-foreground">{video.artist}</p>
                    <Badge variant="secondary" className="text-[8px] font-normal px-1 py-0">
                      {video.artistOrigin}
                    </Badge>
                  </div>
                  <div className="flex items-center gap-2 mt-1 text-xs text-muted-foreground">
                    <span className="flex items-center gap-1">
                      <Eye className="h-3 w-3" />
                      {video.views}
                    </span>
                    <span>{getTimeAgo(video.publishedAt)}</span>
                  </div>
                </a>
              </article>
            ))}
          </div>
        </section>
      </div>
    </div>
  )
}
